<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PostAnvilSourceRoot>$(MSBuildThisFileDirectory)..\PostAnvil DSL\PostAnvil</PostAnvilSourceRoot>
    <AntlrRuntimeRoot Condition="'$(AntlrRuntimeRoot)'==''">D:\UserBin\antlr-vs2022-runtime</AntlrRuntimeRoot>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <SDLCheck>true</SDLCheck>
      <ConformanceMode>true</ConformanceMode>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
      <PreprocessorDefinitions>ANTLR4CPP_STATIC;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>$(PostAnvilSourceRoot)\include;$(PostAnvilSourceRoot)\antlr4;$(PostAnvilSourceRoot)\tests;$(AntlrRuntimeRoot)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <AdditionalDependencies>antlr4-runtime.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories Condition="'$(Platform)'=='x64'">$(AntlrRuntimeRoot)\x64\lib\$(Configuration) Static;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <Manifest>
      <EnableSegmentHeap>true</EnableSegmentHeap>
    </Manifest>
  </ItemDefinitionGroup>
</Project>
