name: python-wheels

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v3.3
        with:
          package-dir: .
          output-dir: wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}
          path: wheelhouse/*.whl
